
const Maroon         = rgb(128,   0,   0)
const ForestGreen    = rgb( 34, 139,  34)
const Navy           = rgb(  0,   0, 128)
const DarkRed        = rgb(139,   0,   0)
const Lime           = rgb(  0, 255,   0)
const DarkBlue       = rgb(  0,   0, 139)
const Brown          = rgb(165,  42,  42)
const LimeGreen      = rgb( 50, 205,  50)
const MedBlue        = rgb(  0,   0, 205)
const Firebrick      = rgb(178,  34,  34)
const LightGreen     = rgb(144, 238, 144)
const Blue           = rgb(  0,   0, 255) 
const Crimson        = rgb(220,  20,  60)
const PaleGreen      = rgb(152, 251, 152)
const RoyalBlue      = rgb( 65, 105, 225)
const Red            = rgb(255,   0,   0)
const DarkSeaGreen   = rgb(143, 188, 143)
const BlueViolet     = rgb(138,  43, 226)
const Tomato         = rgb(255,  99,  71)
const MedSpringGreen = rgb(  0, 250, 154)
const Indigo         = rgb( 75,   0, 130)
const Coral          = rgb(255, 127,  80)
const SpringGreen    = rgb(  0, 255, 127)
const DarkSlateBlue  = rgb( 72,  61, 139)
const IndianRed      = rgb(205,  92,  92)
const SeaGreen       = rgb( 46, 139,  87)
const SlateBlue      = rgb(106,  90, 205) 
const LightCoral     = rgb(240, 128, 128)
const MedAquaMarine  = rgb(102, 205, 170)
const MedSlateBlue   = rgb(123, 104, 238)
const DarkSalmon     = rgb(233, 150, 122)
const MedSeaGreen    = rgb( 60, 179, 113)
const MediumPurple   = rgb(147, 112, 219)
const Salmon         = rgb(250, 128, 114)
const LightSeaGreen  = rgb( 32, 178, 170)
const DarkMagenta    = rgb(139,   0, 139)
const LightSalmon    = rgb(255, 160, 122)
const DarkSlateGray  = rgb( 47,  79,  79)
const DarkViolet     = rgb(148,   0, 211)
const OrangeRed      = rgb(255,  69,   0)
const Teal           = rgb(  0, 128, 128)
const DarkOrchid     = rgb(153,  50, 204) 
const DarkOrange     = rgb(255, 140,   0)
const DarkCyan       = rgb(  0, 139, 139)
const MediumOrchid   = rgb(186,  85, 211)
const Orange         = rgb(255, 165,   0)
const Cyan           = rgb(  0, 255, 255)
const Purple         = rgb(128,   0, 128)
const Gold           = rgb(255, 215,   0)
const LightCyan      = rgb(224, 255, 255)
const Thistle        = rgb(216, 191, 216)
const DarkGoldenRod  = rgb(184, 134,  11)
const DarkTurquoise  = rgb(  0, 206, 209)
const Plum           = rgb(221, 160, 221)
const GoldenRod      = rgb(218, 165,  32)
const Turquoise      = rgb( 64, 224, 208)
const Violet         = rgb(238, 130, 238)
const PaleGoldenRod  = rgb(238, 232, 170)
const MedTurqoise    = rgb( 72, 209, 204)
const Magenta        = rgb(255,  10, 255)
const DarkKhaki      = rgb(189, 183, 107)
const PaleTurquoise  = rgb(175, 238, 238)
const Orchid         = rgb(218, 112, 214) 
const Khaki          = rgb(240, 230, 140)
const AquaMarine     = rgb(127, 255, 212)
const MedVioletRed   = rgb(199,  21, 133)
const Olive          = rgb(128, 128,   0)
const PowderBlue     = rgb(176, 224, 230)
const PaleVioletRed  = rgb(219, 112, 147)
const Yellow         = rgb(255, 255,   0)
const CadetBlue      = rgb( 95, 158, 160)
const DeepPink       = rgb(255,  20, 147)
const YellowGreen    = rgb(154, 205,  50)
const SteelBlue      = rgb( 70, 130, 180)
const HotPink        = rgb(255, 105, 180)
const DarkOliveGreen = rgb( 85, 107,  47)
const CornFlowerBlue = rgb(100, 149, 237)
const LightPink      = rgb(255, 182, 193)
const OliveDrab      = rgb(107, 142,  35)
const DeepSkyBlue    = rgb(  0, 191, 255)
const Pink           = rgb(255, 192, 203)
const LawnGreen      = rgb(124, 252,   0)
const DodgerBlue     = rgb( 30, 144, 255)
const AntiqueWhite   = rgb(250, 235, 215)
const ChartReuse     = rgb(127, 255,   0)
const LightBlue      = rgb(173, 216, 230)
const Beige          = rgb(245, 245, 220)
const GreenYellow    = rgb(173, 255,  47)
const SkyBlue        = rgb(135, 206, 235)
const Bisque         = rgb(255, 228, 196)
const DarkGreen      = rgb(  0, 100,   0)
const LightSkyBlue   = rgb(135, 206, 250)
const BlanchedAlmond = rgb(255, 235, 205)
const Green          = rgb(  0, 128,   0)
const MidnightBlue   = rgb( 25,  25, 112)
const Wheat          = rgb(245, 222, 179)
const CornSilk       = rgb(255, 248, 220)
const LavenderBlush  = rgb(255, 240, 245)
const White          = rgb(255, 255, 255)           
const LemonChiffon   = rgb(255, 250, 205)
const Linen          = rgb(250, 240, 230)
const WhiteSmoke     = rgb(245, 245, 245)
const LtYellowGold   = rgb(250, 250, 210)
const OldLace        = rgb(253, 245, 230)
const Gainsboro      = rgb(220, 220, 220)
const LightYellow    = rgb(255, 255, 224)
const PapayaWhip     = rgb(255, 239, 213)
const LightGray      = rgb(211, 211, 211)
const SaddleBrown    = rgb(139,  69,  19)
const SeaShell       = rgb(255, 245, 238)
const Silver         = rgb(192, 192, 192)
const Sienna         = rgb(160,  82,  45)
const MintCream      = rgb(245, 255, 250)
const DarkGray       = rgb(169, 169, 169)
const Chocolate      = rgb(210, 105,  30)
const SlateGray      = rgb(112, 128, 144)
const Gray           = rgb(128, 128, 128)
const Peru           = rgb(205, 133,  63)
const LightSlateGray = rgb(119, 136, 153)
const DimGray        = rgb(105, 105, 105)
const SandyBrown     = rgb(244, 164,  96)
const LightSteelBlue = rgb(176, 196, 222)
const Black          = rgb(  0,   0,   0)
const BurlyWood      = rgb(222, 184, 135)
const Lavender       = rgb(230, 230, 250)
const Snow           = rgb(255, 250, 250)
const Tann           = rgb(210, 180, 140)
const FloralWhite    = rgb(255, 250, 240)
const MistyRose      = rgb(255, 228, 225)      
const RosyBrown      = rgb(188, 143, 143)
const AliceBlue      = rgb(240, 248, 255)
const PeachPuff      = rgb(255, 218, 185)
const Moccasin       = rgb(255, 228, 181)
const GhostWhite     = rgb(248, 248, 255)
const Azure          = rgb(240, 255, 255)
const NovajoWhite    = rgb(255, 222, 173)
const Honeydew       = rgb(240, 255, 240)
const Ivory          = rgb(255, 255, 240) 

' 128,   0,   0 = Maroon           34, 139,  34 = Forest Green        0,   0, 128 = Navy
' 139,   0,   0 = Dark Red          0, 255,   0 = Lime                0,   0, 139 = Dark Blue
' 165,  42,  42 = Brown            50, 205,  50 = Lime Green          0,   0, 205 = Med Blue
' 178,  34,  34 = Firebrick       144, 238, 144 = Light Green         0,   0, 255 = Blue
' 220,  20,  60 = Crimson         152, 251, 152 = Pale Green         65, 105, 225 = Royal Blue
' 255,   0,   0 = Red             143, 188, 143 = Dark Sea Green    138,  43, 226 = Blue Violet
' 255,  99,  71 = Tomato            0, 250, 154 = Med Spring Green   75,   0, 130 = Indigo
' 255, 127,  80 = Coral             0, 255, 127 = Spring Green       72,  61, 139 = Dk Slate Blue
' 205,  92,  92 = Indian Red       46, 139,  87 = Sea Green         106,  90, 205 = Slate Blue 
' 240, 128, 128 = Light Coral     102, 205, 170 = Med Aqua Marine   123, 104, 238 = Med Slate Blue
' 233, 150, 122 = Dark Salmon      60, 179, 113 = Med Sea Green     147, 112, 219 = Medium Purple
' 250, 128, 114 = Salmon           32, 178, 170 = Light Sea Green   139,   0, 139 = Dark Magenta
' 255, 160, 122 = Light Salmon     47,  79,  79 = Dark Slate Gray   148,   0, 211 = Dark Violet
' 255,  69,   0 = Orange Red        0, 128, 128 = Teal              153,  50, 204 = Dark Orchid
' 255, 140,   0 = Dark Orange       0, 139, 139 = Dark Cyan         186,  85, 211 = Medium Orchid
' 255, 165,   0 = Orange            0, 255, 255 = Cyan              128,   0, 128 = Purple
' 255, 215,   0 = Gold            224, 255, 255 = Light Cyan        216, 191, 216 = Thistle
' 184, 134,  11 = Dk Golden Rod     0, 206, 209 = Dark Turquoise    221, 160, 221 = Plum
' 218, 165,  32 = Golden Rod       64, 224, 208 = Turquoise         238, 130, 238 = Violet
' 238, 232, 170 = Pale Golden Rod  72, 209, 204 = Med Turquoise     255,  10, 255 = Magenta
' 189, 183, 107 = Dark Khaki      175, 238, 238 = Pale Turquoise    218, 112, 214 = Orchid
' 240, 230, 140 = Khaki           127, 255, 212 = Aqua Marine       199,  21, 133 = Med Violet Red
' 128, 128,   0 = Olive           176, 224, 230 = Powder Blue       219, 112, 147 = Pale Violet Red
' 255, 255,   0 = Yellow           95, 158, 160 = Cadet Blue        255,  20, 147 = Deep Pink
' 154, 205,  50 = Yellow Green     70, 130, 180 = Steel Blue        255, 105, 180 = Hot Pink
'  85, 107,  47 = Dk Olive Green  100, 149, 237 = Corn Flower Blue  255, 182, 193 = Light Pink 
' 107, 142,  35 = Olive Drab        0, 191, 255 = Deep Sky Blue     255, 192, 203 = Pink
' 124, 252,   0 = Lawn Green       30, 144, 255 = Dodger Blue       250, 235, 215 = Antique White
' 127, 255,   0 = Chart Reuse     173, 216, 230 = Light Blue        245, 245, 220 = Beige
' 173, 255,  47 = Green Yellow    135, 206, 235 = Sky Blue          255, 228, 196 = Bisque
'   0, 100,   0 = Dark Green      135, 206, 250 = Light Sky Blue    255, 235, 205 = Blanched Almond
'   0, 128,   0 = Green            25,  25, 112 = Midnight Blue     245, 222, 179 = Wheat
' 255, 248, 220 = Corn Silk       255. 240, 245 = Lavendar Blush    255, 255, 255 = White           
' 255, 250, 205 = Lemon Chiffon   250, 240, 230 = Linen             245, 245, 245 = White Smoke
' 250, 250, 210 = Lt Yellow Gold  253, 245, 230 = Old Lace          220, 220, 220 = Gainsboro
' 255, 255, 224 = Light Yellow    255, 239, 213 = Papaya Whip       211, 211, 211 = Light Gray 
' 139,  69,  19 = Saddle Brown    255, 245, 238 = Sea Shell         192, 192, 192 = Silver
' 160,  82,  45 = Sienna          245, 255, 250 = Mint Cream        169, 169, 169 = Dark Gray
' 210, 105,  30 = Chocolate       112, 128, 144 = Slate Gray        128, 128, 128 = Gray
' 205, 133,  63 = Peru            119, 136, 153 = Light Slate Gray  105, 105, 105 = Dim Gray
' 244, 164,  96 = Sandy Brown     176, 196, 222 = Light Steel Blue    0,   0,   0 = Black
' 222, 184, 135 = Burly Wood      230, 230, 250 = Lavender          255, 250, 250 = Snow
' 210, 180, 140 = Tan             255, 250, 240 = Floral White      255, 228, 225 = Misty Rose      
' 188, 143, 143 = Rosy Brown      240, 248, 255 = Alice Blue        255, 218, 185 = Peach Puff
' 255, 228, 181 = Moccasin        248, 248, 255 = Ghost White       240, 255, 255 = Azure
' 255, 222, 173 = Novajo White    240, 255, 240 = Honeydew          255, 255, 240 = Ivory 






























